apiVersion: v1
kind: Service
metadata:
  name: katalogdogodkov-service
  labels:
    app: katalog-dogodkov
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 32222
  selector:
    app: katalog-dogodkov